# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gaussian Process IRT MCMC
#'
#' Provides posterior samples for the GP-IRT.
#'
#' @param y A matrix of responses; each entry should be -1 or 1
#' @param sample_iterations An integer vector of length one giving the number
#'   of samples to record
#' @param burn_iterations An integer vector of length one giving the number of
#'   burn in (unrecorded) iterations
#'
#' @return A list of length two; the first element, "theta", is a matrix of
#'   dimensions sample_iterations x n giving the theta parameter draws, and the
#'   second element, "f", is an array of dimensions n x m x sample_iterations
#'   giving the f(theta) parameter draws.
#' @export
gpirtMCMC <- function(y, sample_iterations, burn_iterations) {
    .Call(`_gpirt_gpirtMCMC`, y, sample_iterations, burn_iterations)
}

