# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gpirtMCMC <- function(y, theta, sample_iterations, burn_iterations, beta_prior_means, beta_prior_sds, beta_step_sizes) {
    .Call(`_gpirt_gpirtMCMC`, y, theta, sample_iterations, burn_iterations, beta_prior_means, beta_prior_sds, beta_step_sizes)
}

